# Generated by Django 4.2.9 on 2024-01-24 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='stickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
