# Generated by Django 4.2.9 on 2024-01-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='stickers',
        ),
    ]
