# Generated by Django 4.2.9 on 2024-02-05 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_name_albumsticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumsticker',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumsticker',
            name='rarity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
