# Generated by Django 4.2.9 on 2024-02-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_remove_season_current_season'),
        ('album', '0008_alter_album_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.season'),
        ),
    ]
