# Generated by Django 4.2.9 on 2024-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=models.BooleanField(default=False),
        ),
    ]
