# Generated by Django 4.2.9 on 2024-02-06 10:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_current_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='created_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='updated_at',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
