# Generated by Django 4.2.9 on 2024-02-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_season_date_from_season_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='current_season',
        ),
    ]
