# Generated by Django 4.2.9 on 2024-01-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_album_stickers'),
        ('sticker', '0003_sticker_album_sticker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='album.album'),
        ),
    ]
