# Generated by Django 4.2.9 on 2024-02-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0007_stickeruser_sticker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickeruser',
            old_name='quantity',
            new_name='count',
        ),
    ]
